# Generated by Django 5.2.4 on 2025-08-02 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
