# Generated by Django 5.2.4 on 2025-10-21 08:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='reserved_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
