# Generated by Django 5.2.4 on 2025-09-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_user_alter_orderitem_product_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='label',
            field=models.CharField(default='Home', max_length=50),
        ),
    ]
