# Generated by Django 5.2.4 on 2025-09-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_useraddress_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
